### ISSUE TITLE
Multiton instances

### ISSUE THREAD

**Issue by sagikazarmark** [orno/di#37]
Do you plan to implement something like this?

**Comment by philipobenito** [comment]
By default you get a new instance everytime you request an object. The only time the sane instance would be returned is if it's defined to do so by using the singleton method to register it.

If you need multiple instances in different state you can define as many as you like, just give them a different alias.

**Comment by sagikazarmark** [comment]
I think there are many absolutely valid use cases of managing multiple instances of the same resource. (multiple database connections, multiple connections to anywhere, etc) I don't think registering the same resource multiple times is a viable way. The other reason is that the check `isSingleton` begs the question: Is there an `isMultiton` as well?

Since this is some sort of service locator as well, managing multiton instances could easily be part of it. This is something I miss from other dependency containers.

So I imagine it as a sub-alias of the main one, so that creating AND storing an instance of it is easy.

**Comment by philipobenito** [comment]
Well it's prototype by default and very rare that you'd need to actually
register multiple instances.

Whilst the container can be used as a service locator, as all containers
can, I never built it to be one and I don't want to add functionality that
encourages the use of it as a service locator.

There's definitely scope to change the naming convention here as I never
liked the use of singleton as that's not what it is by the definition,
multiple instances are not blocked, the container is just managing it as a
single instance, otherwise it's a new instance every time.
