### ISSUE TITLE
[Q] Orno/DI future?

### ISSUE THREAD

**Issue by Addvilz** [orno/di#41]
It's a little unclear and seems that it's not documented anywhere - is there any future plans for deprecating this package in favor to league/di or anything alike? 

I am currently working on integrating orno/di in to my own project, so it's pretty important to know what's the current heading of the project. :)

For new projects, which one should be targeted - Orno or league?

**Comment by philipobenito** [comment]
I have just finished setting up a new repo under `League\Container` https://github.com/thephpleague/container. This is so that I can aim to phase out some of the Orno packages and concentrate on improving the Container and Router.

If you're not using any of the caching within the container, then it is a straight drop in replacement right now, so all you'll need to do in your app is change the namespace you're accessing from `Orno\Di` to `League\Container`.

**Comment by Addvilz** [comment]
Brilliant, thank you. 

You should, however, put this info up somewhere in repo, just in case some poor soul like me does not get lost.

**Comment by philipobenito** [comment]
Haha, yes, I'm just in the process of updating the README, you literally asked the question about a minute after I'd completed setting up the repo at League :-)
